title: Freddy Asenjo
description: Biotechnology Engineer & Developer
url: "https://znaew.github.io"
baseurl: ""
 
permalink: /blog/:title/
 
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
 
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
 